### ISSUE TITLE
Build / publish wheels on Appveyor

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/Acquisition#24]
Checklist from https://github.com/zopefoundation/zope.proxy/issues/24:

- [x] a copy of `appveyor.yml` from `zope.interface` or similar
- [x] someone with an Appveyor account (e.g. @mgedmin ) to enable this project
- [x] encrypted PyPI upload credentials in the `appveyor.yml` (no change required from the copy in `zope.interface` if @mgedmin is the one who enables the Appveyor account)
- [x] grant **zope.wheelbuilder** PyPI rights
- [x] push the `appveyor.yml` commit to master
- [x] (optionally) a push of a temporary branch that builds and uploads `Acquisition 4.4.2` wheels

**Comment by dataflake** [comment]
Fixed by commits 0b17c44052436633d170f45a9f930252832da60d and e6725597ffef6b8748499cedb09b289cb0c14fb4
