### ISSUE TITLE
Please release a new egg

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Acquisition#25]
#22 may be more widespread, IMHO it will affect all Acquisition-heavy sites since at least Acquisition 2.13.11, which ships with Zope 2.13.26. That's the oldest version I tested.

The symptoms include frequent Python crashes with segfaults pointing to _Acquisition.so, signal 6 (ABORT) crashes with stack traces pointing to GC garbage collection and signal 7 (bus error) crashes.

Please release a new version and eggs, I'm currently relying on a locally-built egg for a customer. Zope 2.13.26 appears to run fine with the current Acquisition fix, ExtensionClass 4.3.0 and as dependency BTreeFolder 3.0.

I would do it myself, but the plethora of binary eggs on PiPI suggests that there's some ready-made rig somewhere to produce them. I can only do source eggs locally.

**Comment by hannosch** [comment]
The Windows binary eggs got produced by the winbot. Since it's gone, appveyor might be able to pick up the work (#24).

The wheels for the manylinux target can be built with the help of the official manylinux Docker container at https://github.com/pypa/manylinux. I have some helper script at https://github.com/hannosch/zope_wheels for this. Those scripts try to mass-build all missing wheels (source and manylinux binary) for all of Zope and the ZTK.

I'll try to cut a new release and build the manylinux wheels soon.

**Comment by dataflake** [comment]
Thanks for pointing me to your zope_wheels repo. As a complete Docker virgin I managed to get it running and building eggs. The one thing I can't figure out right now is in the ``sign.sh`` script, I don't know how to tell ``wheel sign`` to use the key ``gpg`` has set as default signing key.

**Comment by dataflake** [comment]
After looking at the documentation it seems ``wheel`` is not made to use gpg. It wants to use its own internal key.

I'm used to sign on upload with distutils like this: ``python setup.py sdist upload --sign". You seem to do the same  in the manual last step ``twine upload --sign --skip-existing wheelhouse/*.whl`` - so what's that "sign.sh" step for?

**Comment by hannosch** [comment]
The wheel signing stuff is weird. I think the most docs I've seen for it are at https://wheel.readthedocs.io/en/stable/#automatically-sign-wheel-files

Basically you need to run `wheel keygen` once, which on macOS creates a new keypair and stores it in your macOS keychain. After that you can call `wheel sign`. The help text for `wheel --help` has some more pointers and mentions a `RECORD.jws` file which gets included in the wheel.

IIRC the usual setuptools gpg signing creates an extra `.asc` file and uploads it to PyPi. The wheel thing seems to include something into the wheel (zipfile) itself.

I've never really dug into the internals of how this works. If everything is set up correctly (the `WHEEL_TOOL` environment variable is set) calling `bdist_wheel` might even do the wheel signing step automatically. At least the above mentioned docs claim so.

I basically just tried to do the "sign all the things" approach :)

**Comment by dataflake** [comment]
OK, I see. Yes, when I use ``wheel keygen`` to create such a key then the ``sign.sh`` script works. So I'm all set to create those eggs now. 

If you like, I can do the Acquisition egg myself tomorrow morning. I'd call it 4.4.3 instead of 4.5.0, though.

**Comment by dataflake** [comment]
FYI, the new version is tagged and source as well as all of the ``manylinux1`` eggs are on PyPI. Only thing left to do is Windows eggs.

**Comment by hannosch** [comment]
Thanks! Nitpick: It's manylinux wheels not eggs. eggs is the old thing, wheels is the new shiny ;)

**Comment by dataflake** [comment]
By the way, using the (pitiful) instructions at http://python-packaging-user-guide.readthedocs.io/guides/packaging-binary-extensions/#setting-up-a-build-environment-on-windows I managed to build Windows x86 eggs (not x86_64, my one Windows VM is 32 bit only) for Python 3.5 and 3.6. I could not get the build process working for the older Python versions.

**Comment by dataflake** [comment]
Closing this now, I switched to Appveyor wheel building and made a release for that.
