### ISSUE TITLE
PyPy Support: Interest and Feasibility

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/Acquisition#3]
We have a project we're interested in running on PyPy, and one of our current blockers for that is Acquisition. Our project doesn't use all the features of Acquisition and I'm not an Acquisition expert, but as I started noodling around with it over at https://github.com/Nextthought/Acquisition, it started to seem like it should be possible to implement almost all of Acquisition in pure Python in a similar fashion to `zope.proxy`. (A few hours work has about half the test cases passing, although this does seem like a clear place where the 80/20 rule applies.)

I think I have the time to work on such a port now, but before I get too much further I wanted to see if there was any community interest in such a port, and whether such a port is likely to get reviewed/merged. If there is, I'll press ahead with trying to make as complete an implementation as possible (although I'm sure I'll have some questions first), otherwise I'll just focus on small stubs for the things I know our project needs. Of course, if someone already knows of reasons why a port is doomed to failure (I didn't find much traffic about the topic via Google), I'd appreciate hearing that too :)

**Comment by tseaver** [comment]
I would certainly be willing to review a PR which made Acquisition usable on PyPy.  Be sure to add it to `setup.py` (the Trove classifier), and `tox.ini` / `.travis.yml` (to ensure that it doesn't regress).

Also, if you are not already a ZopeFoundation contributor, please [do the dance](http://foundation.zope.org/agreements/ZopeFoundation_Committer_Agreement-2012-01-11.pdf) to become one (you can list me as the "reference contributor").

**Comment by davisagli** [comment]
I would also be willing to review this.

**Comment by jamadden** [comment]
Closed with #4

**Comment by tseaver** [comment]
For future reference, add the following to the commit message of one of the commits in your PR:

```
Closes: #123
```

And then leave the bug open:  It will be closed automagically when the PR is merged.
