### ISSUE TITLE
Converting ImplicitAcquisitionWrapper to bytes fails

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Acquisition#38]
Calling the `bytes` built-in on a `ImplicitAcquisitionWrapper` fails with `AttributeError: __index__`, see the following example:

```python
class A(Implicit):

    def __bytes__(self):
        return b'my bytes'

a = A()
a.b = A()
wrapper = Acquisition.ImplicitAcquisitionWrapper(a.b, a)
bytes(wrapper)
```

The result is `AttributeError: __index__` in the last line. (But when using `str` and `__str__` the return value of the `__str__` method is returned.)

This happens on Python 3.

**Comment by icemac** [comment]
See #39 for a failing test case demonstrating the problem.

Any guidance how to solve the problem would be helpful.

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2019-4-9 06:44 -0700:
>In #39 I already fixed the pure Python implementation, but I have no idea what to do in the C code.

The (acquisition) wrapper must explicitly delegate
special methods to the wrapped object -- because special methods
are not delegated automatically.
For "__str__" this delegation looks like:

static PyObject *
Wrapper_str(Wrapper *self)
{
    PyObject *r;

    if ((r = PyObject_GetAttr(OBJECT(self), py__str__))) {
        ASSIGN(r, PyObject_CallFunction(r,NULL,NULL));
        return r;
    } else {
        PyErr_Clear();
        return PyObject_Str(self->obj);
    }
}

Something similar is required for "__bytes__"
(and maybe other special methods new in Python 3).


The new delegation must be prepared and registered. Search
"_Acquisition.c" for "str" to find appropriate places to put
in the new infrastructure.

**Comment by icemac** [comment]
@d-maurer Thank you for your explanation. The difference between `__str__` and `__bytes__` seems to be that there is a slot for the `__str__` method in the `struct` defined in `_Acquisition.c`:

https://github.com/zopefoundation/Acquisition/blob/e3b5daef0a21380cc4de677a8632877ea2b158aa/src/Acquisition/_Acquisition.c#L1509

The struct itself seems to be a renamed `PyTypeObject` (if I read the C code correctly):

https://github.com/zopefoundation/Acquisition/blob/e3b5daef0a21380cc4de677a8632877ea2b158aa/include/ExtensionClass/ExtensionClass.h#L89

The `PyTypeObject` struct does not know about a `bytes` method, see:

https://github.com/python/cpython/blob/2fb2bc81c3f40d73945c6102569495140e1182c7/Include/cpython/object.h#L177-L266

The implementation of the `bytes` class itself seems to look for `&PyId___bytes__`, which I cannot find anywhere outside the `bytesobject.c` file, (see [bytesobject.c#L2580](https://github.com/python/cpython/blob/2fb2bc81c3f40d73945c6102569495140e1182c7/Objects/bytesobject.c#L2580)). But probably I do not understand the C code correctly.

**Comment by jamadden** [comment]
Right, on Python 3, there is no "slot" for `__bytes__`. That's a named method that must be defined on the type in the `tp_methods` slot. Calling `bytes(obj)` winds up doing `_PyObject_LookupSpecial('__bytes__')`, which does `_PyType_LookupId('__bytes__')` which does `PyType_Lookup('__bytes__')` which calls [`find_name_in_mro`](https://github.com/python/cpython/blob/364f0b0f19cc3f0d5e63f571ec9163cf41c62958/Objects/typeobject.c#L3075) which just walks through the type `__dict__`; earlier, part of initializing the type was to [copy things from `tp_methods` into the `__dict__` using `add_methods`](https://github.com/python/cpython/blob/364f0b0f19cc3f0d5e63f571ec9163cf41c62958/Objects/typeobject.c#L4856)

On Python 2 of course, `bytes` is an alias for `str`, so the `tp_str` slot is used.

**Comment by jamadden** [comment]
`__unicode__` might be an example to follow, it's defined as a method:
```C
static struct PyMethodDef Wrapper_methods[] = {
  ...
  {"__getnewargs__", (PyCFunction)Wrapper___getnewargs__, METH_NOARGS,
    "Get arguments to be passed to __new__"},
  {"__getstate__", (PyCFunction)Wrappers_are_not_picklable, METH_VARARGS,
   "Wrappers are not picklable"},
  {"__reduce__", (PyCFunction)Wrappers_are_not_picklable, METH_VARARGS,
   "Wrappers are not picklable"},
  {"__reduce_ex__", (PyCFunction)Wrappers_are_not_picklable, METH_VARARGS,
   "Wrappers are not picklable"},
  {"__unicode__", (PyCFunction)Wrapper_unicode, METH_NOARGS,
   "Unicode"},
  {NULL,  NULL}
};
```

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2019-4-10 08:36 -0700:
>@d-maurer Thank you for your explanation. The difference between `__str__` and `__bytes__` seems to be that there is a slot for the `__str__` method in the `struct` defined in `_Acquisition.c`:
>
>https://github.com/zopefoundation/Acquisition/blob/e3b5daef0a21380cc4de677a8632877ea2b158aa/src/Acquisition/_Acquisition.c#L1509
>
>The struct itself seems to be a renamed `PyTypeObject` (if I read the C code correctly):
>
>https://github.com/zopefoundation/Acquisition/blob/e3b5daef0a21380cc4de677a8632877ea2b158aa/include/ExtensionClass/ExtensionClass.h#L89
>
>The `PyTypeObject` struct does not know about a `bytes` method, see:

"__bytes__" is apparently defined via "PyMethodDef".

See the "proxy_methods" in "Objects.weakrefobject.c" -- for
the handling of "__bytes__" for the weakref proxy object.

**Comment by icemac** [comment]
Thank you @jamadden and @d-maurer. Implementing `__bytes__` like `__unicode__` seems to do the trick, see #39.
